"""create clinics patients queue_entries tables

Revision ID: e0c513e4ca51
Revises: 
Create Date: 2026-08-06 12:39:23.428711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c513e4ca51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=True)
    op.create_table('queue_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('queue_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'in_consultation', 'completed', 'cancelled', name='queue_status'), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_entries_clinic_id'), 'queue_entries', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_queue_entries_patient_id'), 'queue_entries', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_entries_patient_id'), table_name='queue_entries')
    op.drop_index(op.f('ix_queue_entries_clinic_id'), table_name='queue_entries')
    op.drop_table('queue_entries')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('clinics')
    # ### end Alembic commands ###
