"""Add the `clinics` and `queue_reservations` tables.

Revision ID: 0003_clinic_queues
Revises: 0002_rbac_role_and_ledger_direction
Created: 2026-08-09

The storage behind Mizan Door's clinic queues. Both tables are new, so
unlike `0002` there are no existing rows needing a `server_default` or
a backfill — every column can be `NOT NULL` outright.

Two constraints here are load-bearing rather than decorative:

* **`uq_reservation_clinic_position`** is what actually guarantees no
  two patients hold the same ticket in the same clinic.
  `QueueRepository.join_queue` takes a ``SELECT ... FOR UPDATE`` lock
  on the clinic row to assign tickets sequentially, but a guarantee
  that holds only while every caller remembers to take a lock is not a
  guarantee. This constraint is the one that cannot be forgotten, and
  it is why a duplicate surfaces as a loud `IntegrityError` instead of
  a queue that quietly lies about who is next.

* **`ck_reservation_position_positive`** rules out ticket `0`, which
  would otherwise be indistinguishable from "unset" in a column the
  application always populates.

`status` is rendered as a non-native enum — a ``VARCHAR`` with a
``CHECK`` — so it behaves identically on SQLite and PostgreSQL and can
gain a value later without the `ALTER TYPE` dance a native Postgres
enum would demand.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '0003_clinic_queues'
down_revision: Union[str, None] = '0002_rbac_role_and_ledger_direction'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=200), nullable=False),
    sa.Column('service_rate_minutes', sa.Integer(), nullable=False),
    sa.Column('is_accepting_patients', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('service_rate_minutes > 0', name='ck_clinic_service_rate_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'served', 'cancelled', name='reservation_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('position > 0', name='ck_reservation_position_positive'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'position', name='uq_reservation_clinic_position')
    )
    with op.batch_alter_table('queue_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_reservations_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_reservations_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_reservation_clinic_status', ['clinic_id', 'status'], unique=False)
        batch_op.create_index('ix_reservation_user_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_reservations', schema=None) as batch_op:
        batch_op.drop_index('ix_reservation_user_status')
        batch_op.drop_index('ix_reservation_clinic_status')
        batch_op.drop_index(batch_op.f('ix_queue_reservations_user_id'))
        batch_op.drop_index(batch_op.f('ix_queue_reservations_clinic_id'))

    op.drop_table('queue_reservations')
    op.drop_table('clinics')
    # ### end Alembic commands ###
