"""Add the consultation stage to a queue reservation.

Revision ID: 0004_queue_consultation
Revises: 0003_clinic_queues
Created: 2026-08-09

What "call the next patient" needs in storage:

* **`in_consultation`** joins the `status` enum, between `waiting` and
  `served`. Rendered as a non-native enum (a ``VARCHAR`` plus a
  ``CHECK``), so adding a value is a column widening on every dialect
  rather than the ``ALTER TYPE`` dance a native Postgres enum demands.

* **`called_at` / `completed_at`** record when a patient was admitted
  and when they left. Both nullable, so rows written before this
  migration keep a truthful `NULL` instead of a fabricated timestamp —
  we genuinely do not know when those patients were called. They are
  separate from `updated_at` because any later edit would overwrite
  that, and these two are what let a clinic measure how long people
  really waited and how long consultations really took.

The downgrade needs care in a way the autogenerated version did not
handle: narrowing `status` back to ``VARCHAR(9)`` cannot hold
``'in_consultation'`` (15 characters). Any patient in the room at that
moment is put back to `waiting` first. That is the honest reversal —
the older schema has no notion of being with the clinician, and they
hold the lowest outstanding ticket, so they are simply next in line
again.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '0004_queue_consultation'
down_revision: Union[str, None] = '0003_clinic_queues'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('queue_reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('called_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('waiting', 'in_consultation', 'served', 'cancelled', name='reservation_status', native_enum=False),
               existing_nullable=False)



def downgrade() -> None:
    # Before the column can no longer hold the value: return anyone
    # currently with the clinician to the front of the queue.
    op.execute(
        "UPDATE queue_reservations SET status = 'waiting', called_at = NULL "
        "WHERE status = 'in_consultation'"
    )

    with op.batch_alter_table('queue_reservations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('waiting', 'in_consultation', 'served', 'cancelled', name='reservation_status', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.drop_column('completed_at')
        batch_op.drop_column('called_at')
